#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#

# build Apache Thrift on Travis CI - https://travis-ci.org/

sudo: required

services:
  - docker

install:
  # TODO: Need external repository with master Dockerfile to reuse built layer across builds
  # - docker pull apache/thrift-dev:$DISTRO || true
  - cp -r ./build/docker/scripts/*.sh ./build/docker/$DISTRO/scripts/
  - docker build -q -t thrift-build build/docker/$DISTRO

script:
  - docker run $DOCKER_COMPILER -v $(pwd):/thrift/src -it thrift-build $DOCKER_CMD

env:
  global:
    - TEST_NAME=""
    - DOCKER_CMD="none"
    - DOCKER_COMPILER="-e CC=gcc -e CXX=g++"
    - DISTRO=ubuntu
    - THRIFT_CROSSTEST_CONCURRENCY=8

  matrix:
    - TEST_NAME="Cross Language Tests"
      DOCKER_CMD="../cross-test.sh"

    - TEST_NAME="Autotools (All)"
      DOCKER_CMD="../autotools.sh"
    - TEST_NAME="Autotools (C C++ - Clang)"
      DOCKER_CMD="../autotools.sh --without-csharp --without-java --without-erlang --without-nodejs --without-lua --without-python --without-perl --without-php --without-php_extension --without-dart --without-ruby --without-haskell --without-go --without-haxe --without-d"

    - TEST_NAME="All"
      DOCKER_CMD="../cmake.sh"
    - TEST_NAME="C C++ (Clang)"
      DOCKER_CMD="../cmake.sh -DWITH_PYTHON=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
      DOCKER_COMPILER="-e CC=clang -e CXX=clang++"

    - TEST_NAME="C++ (Boost Thread)"
      DOCKER_CMD="../cmake.sh -DWITH_BOOSTTHREADS=ON -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
    - TEST_NAME="C++ (Boost Thread - Clang)"
      DOCKER_CMD="../cmake.sh -DWITH_BOOSTTHREADS=ON -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
      DOCKER_COMPILER="-e CC=clang -e CXX=clang++"

    - TEST_NAME="C++ (Std Thread)"
      DOCKER_CMD="../cmake.sh -DWITH_STDTHREADS=ON -DCMAKE_CXX_FLAGS='-std=c++11' -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
    - TEST_NAME="C++ (Std Thread - Clang)"
      DOCKER_CMD="../cmake.sh -DWITH_STDTHREADS=ON -DCMAKE_CXX_FLAGS='-std=c++11' -DWITH_PYTHON=OFF -DWITH_C_GLIB=OFF -DWITH_JAVA=OFF -DWITH_HASKELL=OFF"
      DOCKER_COMPILER="-e CC=clang -e CXX=clang++"

    - TEST_NAME="make dist"
      DOCKER_CMD="../make-dist.sh"

    - TEST_NAME="Debian Packages"
      DOCKER_CMD="../dpkg.sh"

    - TEST_NAME="All (CentOS)"
      DOCKER_CMD="../cmake.sh"
      DISTRO=centos

matrix:
  include:
    # QA jobs for code analytics and metrics
    #
    # static code analysis with cppcheck
    # add --error-exitcode=1 to --enable=all as soon as everything is fixed
    - env: TEST_NAME="cppcheck"
      install:
        - sudo apt-get update
        - sudo apt-get install cppcheck
      script:
        # Compiler cppcheck (All)
        - cppcheck --force --quiet --inline-suppr --enable=all -j2 compiler/cpp/src
        # C++ cppcheck (All)
        - cppcheck --force --quiet --inline-suppr --enable=all -j2 lib/cpp/src lib/cpp/test test/cpp tutorial/cpp
        # C Glib cppcheck (All)
        - cppcheck --force --quiet --inline-suppr --enable=all -j2 lib/c_glib/src lib/c_glib/test test/c_glib/src tutorial/c_glib
        # Silent error checks
        - cppcheck --force --quiet --inline-suppr --error-exitcode=1 -j2 compiler/cpp/src
        - cppcheck --force --quiet --inline-suppr --error-exitcode=1 -j2 lib/cpp/src lib/cpp/test test/cpp tutorial/cpp
        - cppcheck --force --quiet --inline-suppr --error-exitcode=1 -j2 lib/c_glib/src lib/c_glib/test test/c_glib/src tutorial/c_glib

    # search for TODO etc within source tree
    # some statistics about the code base
    # some info about the build machine
    - env:    TEST_NAME="TODO FIXME HACK, LoC and system info"
      install:
        - sudo apt-get update
        - sudo apt-get install sloccount
      script:
        - grep -r TODO *
        - grep -r FIXME *
        - grep -r HACK *
        # LoC
        - sloccount .
        # System Info
        - dpkg -l
        - uname -a
